version: '3.8'

services:
  productdb:
    image: mysql:latest
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD: "Abc@123"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"

networks:
  default:
    name: tedu_microservices
    driver: bridge

    #volumes section
volumes:
  mysql_data:
    name: mysql_data
